USE DATABASE ZDJANGO;
USE SCHEMA PUBLIC;
USE WAREHOUSE COMPUTE_GROUP_XS; 

SELECT COUNT(*)  --14 901
FROM ZDJANGO.INSTRUMENT.LINKTABLE
WHERE SOURCEINSTRUMENT LIKE '%CAPITEC%'
ORDER BY ID ASC

/*adding more changes to the script*/ 

SELECT * 
FROM ZDJANGO.INSTRUMENT.INSTRUMENT

/*lets try to commit again*/
