SELECT "COMPANYNAME" AS "FundManager"
,CASE WHEN "SOURCE" in ('GLACIER' ,'MOMENTUM WEALTH','OLD MUTUAL INTERNATIONAL','INVESTEC OFFSHORE','AIMS','GLACIER INTERNATIONAL') AND "INSTRUMENTTYPE"='Equity'
THEN 1
ELSE "ISUTPSP" End AS "UTPSP"
,"SOURCE"||'|'||"SOURCEINSTRUMENT"||'|'||"SOURCEISIN" AS "InstrumentVersionKey"
,CASE WHEN "INSTRUMENT" ='Not Mapped'
THEN "SOURCEINSTRUMENT"
ELSE "INSTRUMENT" End AS "Instrument"
,"INSTRUMENTCLASSNAME" AS "InstrumentClass"
,SOURCEINSTRUMENT AS "%InstrumentKey"
,INSTRUMENTCLASS AS "FundClass"
,SECID AS "FundMorningstarID"
,CASE WHEN "INSTRUMENTDOMICILE"='Not Mapped'
THEN 'Local'
ELSE INSTRUMENTDOMICILE END AS "InstrumentDomicile"
,PSGFUNDTYPE AS "PSGFundType"
,CASE WHEN CATAPPROVALSTATUS1='Not Mapped'
THEN 'Unknown'
ELSE CATAPPROVALSTATUS1 END AS "CAT1Approvalstatus"
,CASE WHEN CATAPPROVALSTATUS2='Not Mapped'
THEN 'Unknown'
ELSE CATAPPROVALSTATUS2 END AS "CAT2Approvalstatus"
,CASE WHEN INSTRUMENT='Not Mapped'
THEN 0
ELSE 1 END AS "_Mapped"
FROM "MASTER_INSTRUMENT"."INSTRUMENT"."VWINSTRUMENT"
WHERE PSGFUNDTYPE = 'Equities'
;
